### ISSUE TITLE
Example of code parameter for creating a new GitHub App

### ISSUE THREAD

**Issue by joshjohanning** [zalexan1996/GithubAPI#1]
[.PARAMETER code](https://github.com/zalexan1996/GithubAPI/blob/main/Functions/Apps/Create-AGithubAppFromAManifest.ps1#L9)

@zalexan1996 Is there an example of the parameter used here?

**Comment by zalexan1996** [comment]
Unfortunately not since there wasn't an example from the doc page it was scraped from. Is it not behaving as it should?

**Comment by joshjohanning** [comment]
I just have no idea what is supposed to go in for `$code` in the API :D

**Comment by zalexan1996** [comment]
I've never created Github Apps before so I'm not exactly sure how this all works, but [this page](https://docs.github.com/en/developers/apps/building-github-apps/creating-a-github-app-from-a-manifest) explains where the authentication code comes from.

**Comment by joshjohanning** [comment]
no worries, thanks!
